import os
import torch

# Access the variables securely
HSA_OVERRIDE_GFX_VERSION = os.getenv("HSA_OVERRIDE_GFX_VERSION")
HIP_VISIBLE_DEVICES = os.getenv("HIP_VISIBLE_DEVICES")
MIOPEN_DEBUG_CONV_IMMED_FIND = os.getenv("MIOPEN_DEBUG_CONV_IMMED_FIND")
MIOPEN_DEBUG_DISABLE_ASM_KERNELS = os.getenv("MIOPEN_DEBUG_DISABLE_ASM_KERNELS")
print(f"HSA_OVERRIDE_GFX_VERSION: {HSA_OVERRIDE_GFX_VERSION}")
print(f"HIP_VISIBLE_DEVICES {HIP_VISIBLE_DEVICES}")
print(f"MIOPEN_DEBUG_CONV_IMMED_FIND: {MIOPEN_DEBUG_CONV_IMMED_FIND}")
print(f"MIOPEN_DEBUG_DISABLE_ASM_KERNELS: {MIOPEN_DEBUG_DISABLE_ASM_KERNELS}")
x = torch.rand(5, 3)
print(x)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))
